### ISSUE TITLE
need to clear processing list of traces after trim() in plot_graph()

### ISSUE THREAD

**Issue by paitor** [bonaime/seedlink_plotter#19]
Hi Guys

Since I have not yet had the time to learn how github works I report on this here instead and let you sort out if this is worth fixing or not.

Problem:
Every time the trim() method of a Stream or Trace object is used an entry is added to the list Trace.stats.processing, thus if the seedlink_plotter is run 24/7 with an update time of 1s this list will eventually grow large. 

Solution:
I therefore suggest to loop over the traces after each use of the trim() method  invocation and pop the last entry of trace_i.stats.processing

regP

**Comment by megies** [comment]
Good point. We can just set the processing to an empty list whenever we append packages to it..
