### ISSUE TITLE
Localisation bug

### ISSUE THREAD

**Issue by bonaime** [bonaime/seedlink_plotter#22]
Today,
A very strange event appeared on my 4 seedlink_plotters : a 7.0m earthquake in North Algeria which does not exist.
Each morning I start those seedlink_plotters at 8:00 UTC. The earthquake origin is around 00:42, more than 7 hours before I started my programs.
After restarting seedlink_plotters, the event is gone. 
   
![capture d ecran 2016-01-14 a 14-01-16 09 57 20](https://cloud.githubusercontent.com/assets/750709/12320047/993b9e1c-baa6-11e5-9ec3-50dff1d46864.png)

**Comment by bonaime** [comment]
On the NERIES site
http://www.seismicportal.eu/
I can see sometimes this 7.0 event ! There should be a bug in NERIES website.

**Comment by megies** [comment]
Ideally, you should report this upstream to the catalog contributor..
