### ISSUE TITLE
seedlink_plotter embedded in a web page

### ISSUE THREAD

**Issue by kiriaki** [bonaime/seedlink_plotter#27]
Hello.
Have you tried to run your code with apache and mod_wsgi for displaying real-time plots in the web? 

Thank you in advance.

**Comment by megies** [comment]
I've never tried anything like this with this TKagg based solution and to be fair to other solutions out there, you might want to also have a look at [crotwell/seisplotjs-seedlink](https://github.com/crotwell/seisplotjs-seedlink):

http://www.seis.sc.edu/~crotwell/seisplotjs_demo/realtime/multipleChans.html

CC @crotwell

**Comment by kiriaki** [comment]
Thank you!! I'll have a look.

**Comment by crotwell** [comment]
Be aware that this doesn't work with all seedlink servers. The ringserver
from IRIS has added the ability to accept an http connection and then
upgrade it to a websocket. Once this happens, then normal seedlink commands
and packets are sent back and forth. But the browser is prevented from
making a generic socket connection, so the server needs that extra ability.
I will update the docs to say this. Would be really nice one day for all
seedlink servers to support this as well.

That said, running a IRIS ringserver in between an existing server and the
web might be an option for realtime displays.

Philip

**Comment by kiriaki** [comment]
Dear Philip, thank you very much for the reply and the valuable information.
I've installed IRIS ring server and the plotting works like a charm :)
I've one question but I'll rather open an issue in seisplotjs-seedlink git page.

Thank you both again!
